language: objective-c
os: osx
sudo: required
python: '3.6'
git:
  depth: 3
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="6.0.0"
  - FFMPEG="https://ffmpeg.zeranoe.com/builds/macos64/shared/ffmpeg-latest-macos64-shared.zip"
  - MEDIAINFO="https://mediaarea.net/download/binary/mediainfo/18.03.1/MediaInfo_CLI_18.03.1_Mac.dmg"
  - secure: Bp08X7e59JRd3Gm5O2h0LCy80MIrDxDZhXyLegQKz8tNNddGrT79IE/YrsVCz092i+iANp+XK2DK/8sEsZcFKtHe6LTAK1y2IlOJQCDWewV8YDAzWeb0Hvr/uOMPZZailFVk3UvPAdLwm/N1/1F2nigAhfYswxTwYHHQ5mk6MlRZVN6O65fALQq9TIDI+O6sIam2K0LfX/mhFkUPvqHRlrfJj5Uijrm8GP9GTDm4ioiuh6ebPmwQ07OZ4B1HJ5Wbwxm5ff1+tCqSDcwsEZonxqgjYb66BCTa44p3C6DYd/bPpepvub3p3I5AugNo4iYzHSLJDmZNhPTpToC442eK58QKXj+GzbeVAOh2+w/YwPqQCkvQPT40UhAEOy4tiYdyatH2bt1hs0QbNxPBYmWvhFceEqtfW67pF08OyJ46CM28uJq3V6Q8C+TegpwLgi7rNaVKD2mU6ylyr855GXlxJfjILNkEq1Dfvm5XsFvUHPc0fPTEbteREgn+Qw6rtctTJ//rLdPcvxOXUfiCWM98wvMFqAA9X/TNHXK0IOlLA/K6HjhzjikXgW/xUcQdYj59AUlUlPAsIkUl6nXoJ9Hj9McohfdR1YTJEXBeHQpoyhmbA9IfBRulxu7+anuVNlF00Xr/UUi8IlTCs00rMLs3dd2DTboN/SV/0TvDH0S+J7M=

before_install:
- brew install aria2 python3 mpv
- pip3 install -U pip pyqt5 pyinstaller
- npm install -g appdmg

install:
- wget https://github.com/ozmartian/vidcutter/archive/${BUILD_VERSION}.tar.gz -O ./vidcutter.tar.gz
- tar -xvf ./vidcutter.tar.gz
- mv vidcutter-${BUILD_VERSION}/* .
- rm -rf vidcutter.tar.gz vidcutter-${BUILD_VERSION}
- python3 setup.py build_ext -i
- mkdir -p bin
- mkdir -p temp && cd temp
- wget ${FFMPEG}
- unzip "${FFMPEG##*/}" ffmpeg-latest-macos64-shared/bin/*
- rm -f ffmpeg-latest-macos64-shared/bin/ffplay ffmpeg-latest-macos64-shared/bin/ffserver
- mv ffmpeg-latest-macos64-shared/bin/* ../bin/
- wget ${MEDIAINFO}
- mkdir -p /tmp/.mnt
- yes Y | hdiutil attach "${MEDIAINFO##*/}" -mountpoint "/tmp/.mnt" -nobrowse
- pkgutil --expand /tmp/.mnt/mediainfo.pkg /tmp/mediainfo.unpkg
- cat /tmp/mediainfo.unpkg/Payload | gzip -d | cpio -id
- mv usr/local/bin/mediainfo ../bin
- cd ..

script:
- cd _build/pyinstaller
- "./build.pyinstaller.osx"
- appdmg dmg.spec.json VidCutter-${BUILD_VERSION}-macOS.dmg
- mv VidCutter-${BUILD_VERSION}-macOS.dmg "${TRAVIS_BUILD_DIR}"
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "Pete Alexandrou"
- git config --local user.email "pete@ozmartians.com"
- git tag -d ${BUILD_VERSION}
- git remote set-url origin https://ozmartian:${GITHUB_TOKEN}@github.com/ozmartian/vidcutter-osx.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api_key:
    secure: uIOb3ThqkTLJ9LZ5mUpL+0CFqmQEyON1gCbr88jOaG1oht8kDyrQSatgQbfeRFJ39nmPVRRPauLZ1ojIhHS2JdGB1u1lteeyOG8NNxXoV3eSGWDpTVTLiS1GkdGx64Z5gEBna4JUh3QYDO12F63KQp0myXOB7F3qco5JdvIxdYi3kIBSeQYFUWvja2m9Dqh2Mms9YfjO8P+Sl+DZ64fjPccI646/+6F+JJDf8OnUCa0qR/t8xFAssaXs9WO+af5zr6zigqE1NkpyLuSLvO4/CY/Ca3TaqOR4Miqvb2Fib9qu3hWsHUTXU/ZTxBvCB5cs+RsAiySSiY9ZHaAU6Ohq9II09yRgDMh8USxyLXdA8886AbQqcfoAWhJYCBbgd2/nVToqxsKMFZRS3s9J9JA6biZ8IJnawbNWhWCuo1bUkrD7Se2hzMs4CQZu2nyqoPLVhFofZTR9fQciDKHfoaxaoreEyLQ9StjyWwipdhTfFms9BCGoFyiTavU48db4OApdJidBuyyw4baB0qreCPSPxtbVgAHS2hakIGIV/NMagNARGh/vpg6V8aHCEso+RX+bW+tGF91xnnOpBfUR77s65r++5p6hpPL9U2ptUp9F/CfCdrhtzT1iqVGv5te0t/bkwRMgn0IXH72PDHDXyaYGAZ3c1fLZjImoMmeC3ay5sd8=
  file: "${TRAVIS_BUILD_DIR}/VidCutter-${BUILD_VERSION}-macOS.dmg"
  overwrite: true
  skip_cleanup: true
  on:
    repo: ozmartian/vidcutter-osx
